services:
  rls-postgres:
    image: postgres:17
    container_name: rls-postgres
    environment:
      POSTGRES_DB: sample_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sample_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  spring-postgres-rls-sample:
    build:
      context: ..
      dockerfile: spring-postgres-rls-sample/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://rls-postgres:5432/sample_db
      SPRING_DATASOURCE_USERNAME: sample_user
      SPRING_DATASOURCE_PASSWORD: sample_password
    depends_on:
      rls-postgres:
        condition: service_healthy

volumes:
  postgres_data: